url: "https://dotenv-enterprise.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Dotenv Enterprise" # the name of your site, e.g. ACME Corp.
logo: "https://raw.githubusercontent.com/motdotla/dotenv/master/dotenv.svg"
description: "Enterprise solutions for your env files."

# Footer "Edit this page on GitHub" link text
github_edit_link: true # show or hide edit this page link
github_edit_link_text: "View on GitHub"
github_edit_repository: "https://github.com/dotenvx/dotenv-enterprise.com" # the github URL for your repo
github_edit_branch: "main" # the branch that your docs is served from
github_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# For SEO Jekyll Plugin
author:
  name: dotenv
  twitter: dotenvx
twitter:
  username: dotenvx
  card: summary
social:
  name: dotenv
  links:
    - https://twitter.com/dotenvx
    - https://github.com/dotenvx
    - https://linkedin.com/company/dotenvx
    - https://www.youtube.com/@dotenvx

defaults:
  - scope:
      path: ""
    values:
      image: "/og-image.png"
      layout: "default"

# For Favicon Plugin
favicon:
  source: "favicon.png"

# Exclude files
exclude:
  - .DS_Store
  - README.md

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true

highlighter: none

plugins:
  - jekyll-redirect-from
  - liquid_pluralize
  - jekyll-timeago
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-favicon
  - jekyll-feed
  - jemoji
  - jekyll-gzip
  - jekyll-loading-lazy
  - jekyll-postcss

postcss:
  cache: false

# include well-known, otherwise jekyll ignore . folders and files
include:
  - .well-known
